### ISSUE TITLE
Incompatible with EdgeOS 2.0.8 on ERX

### ISSUE THREAD

**Issue by cyberkitsune** [jaysoffian/eap_proxy#33] opened 2020-03-26 00:21 UTC
After upgrading to EdgeOS 2.0.8, EAP Proxy stops working. Sample output from with `--debug`

```
[2020-03-23 23:39:55,325]: proxy_loop starting
[2020-03-23 23:40:06,193]: eth1: dc:7f:a4:c9:2d:d0 > 01:80:c2:00:00:03, EAPOL start (1) v2, len 0
[2020-03-23 23:40:06,199]: eth0.0: no IP address
[2020-03-23 23:40:06,204]: eth1: dc:7f:a4:c9:2d:d0 > 01:80:c2:00:00:03, EAPOL start (1) v2, len 0 > eth0
[2020-03-23 23:40:06,208]: eth0: sent 60 bytes
[output repeats forever]
```

Reverting to 1.10.X fixes the issue, but I'd really like 2.0.X to be supported on EdgeRouter-X :)

**Comment by svaj** [comment] 2020-04-03 05:00
I can confirm this behavior, tested with `v1.10.11` and `v2.0.8-hotfix.1`  v2 didn't work, downgrading to v1 did.

**Comment by jaysoffian** [comment] 2020-06-01 17:49
I'm still using EdgeOS v1.10.10. I'll resolve this issue once I upgrade unless someone provides a patch in the meantime. There's not enough information in this report to know what's wrong.

**Comment by tylercal** [comment] 2020-06-01 18:30
FWIW, I’m on 2.0.8 with an edge router 5 PoE, and it’s still working for me.

**Comment by negotiamini** [comment] 2020-06-01 19:46
I got it to work with Edegerouter 12p with no problems

**Comment by jimbair** [comment] 2020-06-01 20:14
I am configuring a brand new er-4 which I can flash to the latest version if it were to be helpful :)

**Comment by prgaly** [comment] 2020-06-16 19:29
FWIW, it worked fine with ER-X 2.0.8-hotfix1 - followed a mostly [these](https://github.com/Genghis1227/guide_eap_proxy) instructions - did not reset my original ERX config - just made minor (firewall names etc.) changes to the commands and used the scripts from this repo as-is. Both IPV4 and IPV6 work fine with good throughput. (Had to disable Smart Queue for that part btw.)

**Comment by prgaly** [comment] 2020-06-21 22:22
> I am configuring a brand new er-4 which I can flash to the latest version if it were to be helpful :)

Worked for me on a  new ER-4 w/2.0.8-hf1 as well. IPV6 is somewhat of a pain but that's working too.

**Comment by jaysoffian** [comment] 2020-08-04 16:11
Closing since there are now multiple reports of `eap_proxy` working on 2.x.

**Closed by jaysoffian** 2020-08-04 16:11 UTC
